services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"  
      - "8920:8920"  
    volumes:
      - ./jellyfin/config:/config  
      - ./jellyfin/cache:/cache    
      - ./media:/media
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Helsinki
      - PORT=5055 
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr/config:/app/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878" 
    environment:
      - PUID=${GROUP_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./radarr/config:/config        
      - ./media/movies:/movies     
      - ./media/downloads:/downloads 
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989" 
    environment:
      - PUID=${GROUP_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr/config:/config    
      - ./media/tvshows:/tv         
      - ./media/downloads:/downloads 
    restart: unless-stopped

  #prowlarr:
  #  image: lscr.io/linuxserver/prowlarr:latest
  #  container_name: prowlarr
  #  ports:
  #    - "9696:9696" 
  #  environment:
  #    - PUID=${GROUP_ID}
  #    - PGID=${GROUP_ID}
  #    - TZ=${TIMEZONE}
  #  volumes:
  #    - ./prowlarr/config:/config
  #  restart: unless-stopped

